---
sortOptions:
  order: fifo
resources:
  - manila-mariadb-database.yaml
  - manila-rabbitmq-queue.yaml
  - all.yaml
  - hpa-manila-api.yaml
  - hpa-manila-data.yaml
  - hpa-manila-scheduler.yaml
  - hpa-manila-share.yaml
  - manila-rabbitmq-queue-policy.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: manila-share
    path: patch-manila-share-ssh-keypair.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: manila-share
    path: patch-manila-host-network.yaml
